require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.1
  NewCops: enable
  Exclude:
    - "assets/**/*"
    - "bin/**/*"
    - "db/schema.rb"
    - "log/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "config/environments/development.rb"
    - "db/migrate/*.rb"
    - "spec/requests/*.rb"

# 日本語のコメントを許可
Style/AsciiComments:
  Enabled: false

# ドキュメントの無い public class を許可
Style/Documentation:
  Enabled: false

# frozen_string_literal の指定強制を解除
Style/FrozenStringLiteralComment:
  Enabled: false

# 1行の最大
Layout/LineLength:
  Max: 160

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

# 変数の代入(A)、メソッドの呼び出し等(B)、条件分岐(C)から算出される複雑度
Metrics/AbcSize:
  Max: 30

# 循環的複雑度 ≒ 分岐の数
Metrics/CyclomaticComplexity:
  Max: 10

# 1行の文字数
Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"
    - "spec/requests/*.rb"

# メソッドの行数
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"
